//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStoreSalesSystemSolution.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MusicStoreDBEntities : DbContext
    {
        public MusicStoreDBEntities()
            : base("name=MusicStoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<SP_GetProducts_Result> SP_GetProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProducts_Result>("SP_GetProducts");
        }
    
        public virtual ObjectResult<top_five_selling_products_Result> top_five_selling_products()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<top_five_selling_products_Result>("top_five_selling_products");
        }
    
        public virtual ObjectResult<SP_top_five_selling_employee_Result> SP_top_five_selling_employee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_top_five_selling_employee_Result>("SP_top_five_selling_employee");
        }
    
        public virtual ObjectResult<SP_Top_5_Seller_Result> SP_Top_5_Seller()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Top_5_Seller_Result>("SP_Top_5_Seller");
        }
    }
}
